function HurricaneDataSmall = importfile6(workbookFile, sheetName, dataLines)
%IMPORTFILE6 Import data from a spreadsheet
%  HURRICANEDATASMALL = IMPORTFILE6(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a timetable.
%
%  HURRICANEDATASMALL = IMPORTFILE6(FILE, SHEET) reads from the
%  specified worksheet.
%
%  HURRICANEDATASMALL = IMPORTFILE6(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  HurricaneDataSmall = importfile6("C:\Users\lsammon\MATLAB Drive\1_Seminars\Intro to Data Analysis with MATLAB\Hurricane Wind\Data\HurricaneDataSmall.xlsx", "Ana", [3, Inf]);
%
%  See also READTIMETABLE.
%
% Auto-generated by MATLAB on 15-Jul-2025 10:38:03

%% Input handling

% If no sheet is specified, read from Ana
if nargin == 1 || isempty(sheetName)
    sheetName = "Ana";
end

% If row start and end points are not specified, define defaults
lastRowOfDataIdx = 0;
if nargin <= 2
    dataLines = [3, Inf];
    lastRowOfDataIdx = 1;
elseif dataLines(end,2) >= Inf
    lastRowOfDataIdx = size(dataLines, 1);
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = sheetName;
if lastRowOfDataIdx == 1
    opts.DataRange = "A" + dataLines(1, 1);
else
    opts.DataRange = "A" + dataLines(1, 1) + ":H" + dataLines(1, 2);
end

% Specify column names and types
opts.VariableNames = ["Var1", "Time", "Type", "Lat", "Lon", "MaxWind", "Var7", "Cat"];
opts.SelectedVariableNames = ["Time", "Type", "Lat", "Lon", "MaxWind", "Cat"];
opts.VariableTypes = ["char", "double", "categorical", "double", "double", "double", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Type", "Var7"], "EmptyFieldRule", "auto");

% Import the data
HurricaneDataSmall = readtimetable(workbookFile, opts, "UseExcel", false, "RowTimes", "Timstamp");

for idx = 2:size(dataLines, 1)
    if idx == lastRowOfDataIdx
        opts.DataRange = "A" + dataLines(idx, 1);
    else
        opts.DataRange = "A" + dataLines(idx, 1) + ":H" + dataLines(idx, 2);
    end
    tb = readtimetable(workbookFile, opts, "UseExcel", false, "RowTimes", "Timstamp");
    HurricaneDataSmall = [HurricaneDataSmall; tb]; %#ok<AGROW>
end

end